version: '2.3'
services:
    cloud9:
        build: cloud9/
        volumes:
            - ./ssh:/root/.ssh
            - /workspace:/cloud9/workspace
        ports:
            - "127.0.0.1:8000:8080"
    jupyter:
        build: jupyter/
        volumes:
            - ./ssh:/root/.ssh
            - /workspace:/workspace
        ports:
            - "127.0.0.1:8100:8888"
    nteract:
        build: nteract/
        volumes:
            - ./ssh:/root/.ssh
            - /workspace:/workspace
        ports:
            - "127.0.0.1:8200:8888"
